### PR TITLE
T3 & INRA/Whealbi wheat traits

### PR DESCRIPTION
**Pull request by cpommier**
Empty fields are not double quoted, hence generating a lot of noise.

### CODE REVIEW

**Comment by cpommier** [comment]
@marieALaporte There is a conflict, I will have a look into it.

**Comment by marieALaporte** [comment]
For some reasons, I was not able to create the PR. So thanks for creating it. I can take a look to the conflicts too

**Comment by cpommier** [comment]
Apparently the conflict is due to the double quotes problem. @marieALaporte I see two possibilities.
- Update master to remove all empty double quotes : "" . Then redo the pull request and we should be good.
- Do the merge by hand on the command line.

What do you think ?

**Comment by marieALaporte** [comment]
@cpommier it would be cleaner to do it the other way around, and fix the issue in the branch

**Comment by cpommier** [comment]
Yes you are rigth, simply reverting the commit is better.

**Comment by cpommier** [comment]
Commit reverted, is it better on your side @marieALaporte ?

**Comment by cpommier** [comment]
@marieALaporte let me know if you need me to do something more

**Comment by marieALaporte** [comment]
still some issues to fix, mainly on scales that have shifted.

**Comment by cpommier** [comment]
I'll have a look at it this afternoon, thanks

**Comment by cpommier** [comment]
@marieALaporte could you mention the line with the shifted scales please ? Thanks

**Comment by marieALaporte** [comment]
@cpommier  704, 705, 706, 708, 709, 716, 718, 725, 729, 735, 776, 781, 783, 784, 798, 805, 809, 823

**Comment by cpommier** [comment]
Thanks @marieALaporte  those are the T3 variables, that's why I missed them. I correct this before 14h00 (this should be ok)

**Comment by marieALaporte** [comment]
great @cpommier, thanks. Merging now

**Pull request merged**
